# Site settings
title: Journey Through Code
email: KristinDragos@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Once a teacher, now I'm learning to code some amazing things. 
  Join me on my journey as I learn more about coding and myself.  

baseurl: "/Blog/" # the subpath of your site, e.g. /blog/
url: "KDragos.github.io/Blog/" # the base hostname & protocol for your site
twitter_username: MrsDragos
github_username:  KDragos

# Build settings
markdown: kramdown
paginate: 6
paginate_path: "/blog/page:num/"
